"""
plot_fs_comparison.py
---------------------
Overlay experimental ALBA-I f_s measurements (digitized from PPTX)
onto the analytical f_s vs I_sr curves for the three lattice cases.

Requires fs_analytical_alba1_no_hc.txt, fs_analytical_alba2_no_hc.txt,
fs_analytical_alba2_hc.txt in the same directory (generated by fs_analytical.py).

Experimental data (from WebPlotDigitizer), also in the same directory:
    exp_spectrum_analyzer_3MV.csv   -- mandatory
    exp_bbb_3MV.csv                 -- optional
    exp_spectrum_analyzer_2.7MV.csv -- optional
    exp_spectrum_analyzer_2.4MV.csv -- optional
    exp_spectrum_analyzer_2.1MV.csv -- optional

CSV format (two columns, with or without header):
    X,Y          <- X = Current [mA], Y = f_s [kHz]
    0.0,8.54
    ...
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Analytical inputs and the output figure live under results/fs_vs_I/;
# the experimental CSVs are tracked inputs and stay next to this script.
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
OUTDIR = os.path.join(REPO_ROOT, "results", "fs_vs_I")
os.makedirs(OUTDIR, exist_ok=True)

COLORS = {
    "alba1_no_hc": "tab:blue",
    "alba2_no_hc": "tab:green",
    "alba2_hc":    "tab:red",
}
LABELS = {
    "alba1_no_hc": "ALBA-I, no HC (analytical)",
    "alba2_no_hc": "ALBA-II, no HC (analytical)",
    "alba2_hc":    "ALBA-II, HC goal 170 kV/cav (analytical)",
}

# ---------------------------------------------------------------------------
# 1. Load theoretical curves from fs_analytical_<case>.txt
# ---------------------------------------------------------------------------

def load_analytical(case_key):
    path = os.path.join(OUTDIR, f"fs_analytical_{case_key}.txt")
    if not os.path.isfile(path):
        print(f"  (not found) {path}")
        return None, None
    data = np.loadtxt(path)          # columns: I_sr[mA]  f_s[Hz]
    print(f"  Loaded analytical {case_key} ({len(data)} points)")
    return data[:, 0], data[:, 1] / 1e3   # mA, kHz

# ---------------------------------------------------------------------------
# 2. Load experimental CSV files
# ---------------------------------------------------------------------------

def load_csv(fname):
    path = os.path.join(SCRIPT_DIR, fname)
    if not os.path.isfile(path):
        return None, None
    try:
        df = pd.read_csv(path, header=None, sep=None, engine='python')
        # Drop header row if first entry is non-numeric
        try:
            float(df.iloc[0, 0])
        except (ValueError, TypeError):
            df = df.iloc[1:].reset_index(drop=True)
        df = df.apply(pd.to_numeric, errors='coerce').dropna()
        x, y = df.iloc[:, 0].values, df.iloc[:, 1].values
        order = np.argsort(x)
        print(f"  Loaded {len(x)} exp. points from {fname}")
        return x[order], y[order]
    except Exception as e:
        print(f"  Could not read {fname}: {e}")
        return None, None

EXP_FILES = [
    ("exp_spectrum_analyzer_3MV.csv",
     dict(marker='o', color='steelblue',      ms=6, zorder=5,
          label='ALBA-I meas. (Spec. an., 3 MV)')),
    ("exp_bbb_3MV.csv",
     dict(marker='s', color='mediumpurple',   ms=5, zorder=4,
          label='ALBA-I meas. (BBB, 3 MV)')),
    ("exp_spectrum_analyzer_2.7MV.csv",
     dict(marker='^', color='cornflowerblue', ms=5, zorder=4,
          label='ALBA-I meas. (Spec. an., 2.7 MV)')),
    ("exp_spectrum_analyzer_2.4MV.csv",
     dict(marker='v', color='royalblue',      ms=5, zorder=4,
          label='ALBA-I meas. (Spec. an., 2.4 MV)')),
    ("exp_spectrum_analyzer_2.1MV.csv",
     dict(marker='D', color='navy',           ms=5, zorder=4,
          label='ALBA-I meas. (Spec. an., 2.1 MV)')),
]

# ---------------------------------------------------------------------------
# 3. Plot
# ---------------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(7, 5))

for key in ("alba1_no_hc", "alba2_no_hc", "alba2_hc"):
    I, fs = load_analytical(key)
    if I is not None:
        ax.plot(I, fs, color=COLORS[key], lw=2.0, ls='-', label=LABELS[key])

for fname, kw in EXP_FILES:
    x, y = load_csv(fname)
    if x is not None:
        ax.plot(x, y, ls='none', **kw)

ax.set_xlabel(r'Stored current $I_{sr}$ [mA]',                   fontsize=12)
ax.set_ylabel(r'Coherent synchrotron frequency $f_s$ [kHz]',     fontsize=12)
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 355)
ax.set_ylim(bottom=0)
ax.xaxis.set_minor_locator(ticker.AutoMinorLocator(5))
ax.yaxis.set_minor_locator(ticker.AutoMinorLocator(5))
ax.legend(fontsize=9, loc='upper center', bbox_to_anchor=(0.5, -0.14),
          ncol=2, framealpha=0.9)
fig.tight_layout()
outfile = os.path.join(OUTDIR, 'fs_comparison.pdf')
fig.savefig(outfile, dpi=200, bbox_inches='tight')
print(f"\nFigure saved to {outfile}")
